INSERT INTO celestial_bodies (body_name, orbits, body_type_id) VALUES
('Universe', NULL, 11);

CALL insert_celestial_body('Milky Way', 'Universe', 'Galaxy');
CALL insert_celestial_body('Andromeda Galaxy', 'Universe', 'Galaxy');
CALL insert_celestial_body('Triangulum Galaxy', 'Universe', 'Galaxy');
CALL insert_celestial_body('Large Magellanic Cloud', 'Universe', 'Galaxy');
CALL insert_celestial_body('Small Magellanic Cloud', 'Universe', 'Galaxy');
CALL insert_celestial_body('Canis Major Dwarf Galaxy', 'Universe', 'Galaxy');
CALL insert_celestial_body('Draco Dwarf Galaxy', 'Universe', 'Galaxy');
CALL insert_celestial_body('Ursa Minor Dwarf Galaxy', 'Universe', 'Galaxy');
CALL insert_celestial_body('Sculptor Dwarf Galaxy', 'Universe', 'Galaxy');
CALL insert_celestial_body('Sextans Dwarf Galaxy', 'Universe', 'Galaxy');
CALL insert_celestial_body('Fornax Dwarf Galaxy', 'Universe', 'Galaxy');
CALL insert_celestial_body('Leo I', 'Universe', 'Galaxy');
CALL insert_celestial_body('Leo II', 'Universe', 'Galaxy');
CALL insert_celestial_body('Tucana Dwarf Galaxy', 'Universe', 'Galaxy');
CALL insert_celestial_body('Carina Dwarf Galaxy', 'Universe', 'Galaxy');
CALL insert_celestial_body('Centaurus A', 'Universe', 'Galaxy');
CALL insert_celestial_body('Messier 87', 'Universe', 'Galaxy');
CALL insert_celestial_body('Whirlpool Galaxy', 'Universe', 'Galaxy');
CALL insert_celestial_body('Sombrero Galaxy', 'Universe', 'Galaxy');
CALL insert_celestial_body('Pinwheel Galaxy', 'Universe', 'Galaxy');
CALL insert_celestial_body('Cartwheel Galaxy', 'Universe', 'Galaxy');
CALL insert_celestial_body('Cigar Galaxy', 'Universe', 'Galaxy');
CALL insert_celestial_body('Bode''s Galaxy', 'Universe', 'Galaxy');
CALL insert_celestial_body('Sunflower Galaxy', 'Universe', 'Galaxy');
CALL insert_celestial_body('Black Eye Galaxy', 'Universe', 'Galaxy');
CALL insert_celestial_body('Tadpole Galaxy', 'Universe', 'Galaxy');
CALL insert_celestial_body('Hoag''s Object', 'Universe', 'Galaxy');
CALL insert_celestial_body('Antennae Galaxies', 'Universe', 'Galaxy');
CALL insert_celestial_body('Mice Galaxies', 'Universe', 'Galaxy');
CALL insert_celestial_body('Southern Pinwheel Galaxy', 'Universe', 'Galaxy');
CALL insert_celestial_body('Messier 81', 'Universe', 'Galaxy');
CALL insert_celestial_body('NGC 1300', 'Universe', 'Galaxy');
CALL insert_celestial_body('NGC 2207', 'Universe', 'Galaxy');
CALL insert_celestial_body('NGC 3370', 'Universe', 'Galaxy');
CALL insert_celestial_body('NGC 4414', 'Universe', 'Galaxy');
CALL insert_celestial_body('Coma Pinwheel Galaxy', 'Universe', 'Galaxy');
CALL insert_celestial_body('Butterfly Galaxies', 'Universe', 'Galaxy');
CALL insert_celestial_body('Backward Galaxy', 'Universe', 'Galaxy');
CALL insert_celestial_body('Fireworks Galaxy', 'Universe', 'Galaxy');
CALL insert_celestial_body('Needle Galaxy', 'Universe', 'Galaxy');
CALL insert_celestial_body('Sculptor Galaxy', 'Universe', 'Galaxy');
CALL insert_celestial_body('NGC 6872', 'Universe', 'Galaxy');
CALL insert_celestial_body('Malin 1', 'Universe', 'Galaxy');
CALL insert_celestial_body('IC 1101', 'Universe', 'Galaxy');
CALL insert_celestial_body('Baby Boom Galaxy', 'Universe', 'Galaxy');
CALL insert_celestial_body('Cosmos Redshift 7', 'Universe', 'Galaxy');
CALL insert_celestial_body('NGC 4889', 'Universe', 'Galaxy');
CALL insert_celestial_body('ESO 383-76', 'Universe', 'Galaxy');
CALL insert_celestial_body('NGC 262', 'Universe', 'Galaxy');
CALL insert_celestial_body('NGC 1600', 'Universe', 'Galaxy');
CALL insert_celestial_body('UGC 2885', 'Universe', 'Galaxy');
CALL insert_celestial_body('Phoenix Cluster Galaxy', 'Universe', 'Galaxy');
CALL insert_celestial_body('SPT0615-JD', 'Universe', 'Galaxy');
CALL insert_celestial_body('GN-z11', 'Universe', 'Galaxy');
CALL insert_celestial_body('3C 273', 'Universe', 'Galaxy');
CALL insert_celestial_body('APM 08279+5255', 'Universe', 'Galaxy');
CALL insert_celestial_body('NGC 4993', 'Universe', 'Galaxy');
CALL insert_celestial_body('MACS1149-JD1', 'Universe', 'Galaxy');
CALL insert_celestial_body('EGSY8p7', 'Universe', 'Galaxy');
CALL insert_celestial_body('GS-z11-0', 'Universe', 'Galaxy');
CALL insert_celestial_body('Hercules A', 'Universe', 'Galaxy');
CALL insert_celestial_body('WISE J224607.57-052635.0', 'Universe', 'Galaxy');
CALL insert_celestial_body('TON 618', 'Universe', 'Galaxy');