INSERT INTO celestial_bodies (body_name, orbits, body_type_id) VALUES
('Universe', NULL, 11),
('Milky Way', NULL, 1),
('Andromeda Galaxy', NULL, 1),
('Triangulum Galaxy', NULL, 1),
('Large Magellanic Cloud', NULL, 1),
('Small Magellanic Cloud', NULL, 1),
('Canis Major Dwarf Galaxy', NULL, 1),
('Draco Dwarf Galaxy', NULL, 1),
('Ursa Minor Dwarf Galaxy', NULL, 1),
('Sculptor Dwarf Galaxy', NULL, 1),
('Sextans Dwarf Galaxy', NULL, 1),
('Fornax Dwarf Galaxy', NULL, 1),
('Leo I', NULL, 1),
('Leo II', NULL, 1),
('Tucana Dwarf Galaxy', NULL, 1),
('Carina Dwarf Galaxy', NULL, 1),
('Centaurus A', NULL, 1),
('Messier 87', NULL, 1),
('Whirlpool Galaxy', NULL, 1),
('Sombrero Galaxy', NULL, 1),
('Pinwheel Galaxy', NULL, 1),
('Cartwheel Galaxy', NULL, 1),
('Cigar Galaxy', NULL, 1),
('Bode''s Galaxy', NULL, 1),
('Sunflower Galaxy', NULL, 1),
('Black Eye Galaxy', NULL, 1),
('Tadpole Galaxy', NULL, 1),
('Hoag''s Object', NULL, 1),
('Antennae Galaxies', NULL, 1),
('Mice Galaxies', NULL, 1),
('Southern Pinwheel Galaxy', NULL, 1),
('Messier 81', NULL, 1),
('NGC 1300', NULL, 1),
('NGC 2207', NULL, 1),
('NGC 3370', NULL, 1),
('NGC 4414', NULL, 1),
('Coma Pinwheel Galaxy', NULL, 1),
('Butterfly Galaxies', NULL, 1),
('Backward Galaxy', NULL, 1),
('Fireworks Galaxy', NULL, 1),
('Needle Galaxy', NULL, 1),
('Sculptor Galaxy', NULL, 1),
('NGC 6872', NULL, 1),
('Malin 1', NULL, 1),
('IC 1101', NULL, 1),
('Baby Boom Galaxy', NULL, 1),
('Cosmos Redshift 7', NULL, 1),
('NGC 4889', NULL, 1),
('ESO 383-76', NULL, 1),
('NGC 262', NULL, 1),
('NGC 1600', NULL, 1),
('UGC 2885', NULL, 1),
('Phoenix Cluster Galaxy', NULL, 1),
('SPT0615-JD', NULL, 1),
('GN-z11', NULL, 1),
('3C 273', NULL, 1),
('APM 08279+5255', NULL, 1),
('NGC 4993', NULL, 1),
('MACS1149-JD1', NULL, 1),
('EGSY8p7', NULL, 1),
('GS-z11-0', NULL, 1),
('Hercules A', NULL, 1),
('WISE J224607.57-052635.0', NULL, 1),
('TON 618', NULL, 1);