-- Stars in the Milky Way Galaxy
CALL insert_celestial_body('Sun', 'Milky Way', 'Star');
CALL insert_celestial_body('Proxima Centauri', 'Milky Way', 'Star');
CALL insert_celestial_body('Alpha Centauri A', 'Milky Way', 'Star');
CALL insert_celestial_body('Alpha Centauri B', 'Milky Way', 'Star');
CALL insert_celestial_body('Barnard''s Star', 'Milky Way', 'Star');
CALL insert_celestial_body('Sirius A', 'Milky Way', 'Star');
CALL insert_celestial_body('Sirius B', 'Milky Way', 'Star');
CALL insert_celestial_body('Wolf 359', 'Milky Way', 'Star');
CALL insert_celestial_body('Lalande 21185', 'Milky Way', 'Star');
CALL insert_celestial_body('Luyten 726-8 A', 'Milky Way', 'Star');
CALL insert_celestial_body('Luyten 726-8 B', 'Milky Way', 'Star');
CALL insert_celestial_body('Ross 154', 'Milky Way', 'Star');
CALL insert_celestial_body('Ross 248', 'Milky Way', 'Star');
CALL insert_celestial_body('Epsilon Eridani', 'Milky Way', 'Star');
CALL insert_celestial_body('Lacaille 9352', 'Milky Way', 'Star');
CALL insert_celestial_body('Ross 128', 'Milky Way', 'Star');
CALL insert_celestial_body('EZ Aquarii A', 'Milky Way', 'Star');
CALL insert_celestial_body('EZ Aquarii B', 'Milky Way', 'Star');
CALL insert_celestial_body('EZ Aquarii C', 'Milky Way', 'Star');
CALL insert_celestial_body('61 Cygni A', 'Milky Way', 'Star');
CALL insert_celestial_body('61 Cygni B', 'Milky Way', 'Star');
CALL insert_celestial_body('Procyon A', 'Milky Way', 'Star');
CALL insert_celestial_body('Procyon B', 'Milky Way', 'Star');
CALL insert_celestial_body('Struve 2398 A', 'Milky Way', 'Star');
CALL insert_celestial_body('Struve 2398 B', 'Milky Way', 'Star');
CALL insert_celestial_body('Groombridge 34 A', 'Milky Way', 'Star');
CALL insert_celestial_body('Groombridge 34 B', 'Milky Way', 'Star');
CALL insert_celestial_body('Epsilon Indi A', 'Milky Way', 'Star');
CALL insert_celestial_body('Epsilon Indi Ba', 'Milky Way', 'Star');
CALL insert_celestial_body('Epsilon Indi Bb', 'Milky Way', 'Star');
CALL insert_celestial_body('DX Cancri', 'Milky Way', 'Star');
CALL insert_celestial_body('Tau Ceti', 'Milky Way', 'Star');
CALL insert_celestial_body('Gliese 1061', 'Milky Way', 'Star');
CALL insert_celestial_body('YZ Ceti', 'Milky Way', 'Star');
CALL insert_celestial_body('Luyten''s Star', 'Milky Way', 'Star');
CALL insert_celestial_body('Teegarden''s Star', 'Milky Way', 'Star');
CALL insert_celestial_body('Kapteyn''s Star', 'Milky Way', 'Star');
CALL insert_celestial_body('Lacaille 8760', 'Milky Way', 'Star');
CALL insert_celestial_body('Kruger 60 A', 'Milky Way', 'Star');
CALL insert_celestial_body('Kruger 60 B', 'Milky Way', 'Star');
CALL insert_celestial_body('WISE 0855-0714', 'Milky Way', 'Star');
CALL insert_celestial_body('Wolf 1061', 'Milky Way', 'Star');
CALL insert_celestial_body('Van Maanen''s Star', 'Milky Way', 'Star');
CALL insert_celestial_body('Gliese 674', 'Milky Way', 'Star');
CALL insert_celestial_body('Gliese 687', 'Milky Way', 'Star');
CALL insert_celestial_body('Gliese 876', 'Milky Way', 'Star');
CALL insert_celestial_body('Gliese 832', 'Milky Way', 'Star');
CALL insert_celestial_body('Gliese 682', 'Milky Way', 'Star');
CALL insert_celestial_body('Gliese 581', 'Milky Way', 'Star');
CALL insert_celestial_body('Gliese 436', 'Milky Way', 'Star');
CALL insert_celestial_body('HD 219134', 'Milky Way', 'Star');
CALL insert_celestial_body('Kepler-186', 'Milky Way', 'Star');
CALL insert_celestial_body('Kepler-22', 'Milky Way', 'Star');
CALL insert_celestial_body('TRAPPIST-1', 'Milky Way', 'Star');
CALL insert_celestial_body('Vega', 'Milky Way', 'Star');
CALL insert_celestial_body('Arcturus', 'Milky Way', 'Star');
CALL insert_celestial_body('Antares', 'Milky Way', 'Star');
CALL insert_celestial_body('Betelgeuse', 'Milky Way', 'Star');
CALL insert_celestial_body('Rigel', 'Milky Way', 'Star');
CALL insert_celestial_body('Aldebaran', 'Milky Way', 'Star');
CALL insert_celestial_body('Deneb', 'Milky Way', 'Star');
CALL insert_celestial_body('Pollux', 'Milky Way', 'Star');
CALL insert_celestial_body('Fomalhaut', 'Milky Way', 'Star');
CALL insert_celestial_body('Mimosa', 'Milky Way', 'Star');
CALL insert_celestial_body('Regulus', 'Milky Way', 'Star');
CALL insert_celestial_body('Adhara', 'Milky Way', 'Star');
CALL insert_celestial_body('Shaula', 'Milky Way', 'Star');
CALL insert_celestial_body('Castor', 'Milky Way', 'Star');
CALL insert_celestial_body('Gacrux', 'Milky Way', 'Star');
CALL insert_celestial_body('Bellatrix', 'Milky Way', 'Star');
CALL insert_celestial_body('Elnath', 'Milky Way', 'Star');
CALL insert_celestial_body('Miaplacidus', 'Milky Way', 'Star');
CALL insert_celestial_body('Alnilam', 'Milky Way', 'Star');
CALL insert_celestial_body('Regor', 'Milky Way', 'Star');
CALL insert_celestial_body('Alioth', 'Milky Way', 'Star');
CALL insert_celestial_body('Kaus Australis', 'Milky Way', 'Star');
CALL insert_celestial_body('Spica', 'Milky Way', 'Star');
CALL insert_celestial_body('Polaris', 'Milky Way', 'Star');
CALL insert_celestial_body('Alphard', 'Milky Way', 'Star');
CALL insert_celestial_body('Algieba', 'Milky Way', 'Star');
CALL insert_celestial_body('Hadar', 'Milky Way', 'Star');
CALL insert_celestial_body('Menkalinan', 'Milky Way', 'Star');
CALL insert_celestial_body('Dubhe', 'Milky Way', 'Star');
CALL insert_celestial_body('Wezen', 'Milky Way', 'Star');
CALL insert_celestial_body('Alkaid', 'Milky Way', 'Star');
CALL insert_celestial_body('Sargas', 'Milky Way', 'Star');
CALL insert_celestial_body('Avior', 'Milky Way', 'Star');
CALL insert_celestial_body('Atria', 'Milky Way', 'Star');
CALL insert_celestial_body('Alhena', 'Milky Way', 'Star');
CALL insert_celestial_body('Peacock', 'Milky Way', 'Star');
CALL insert_celestial_body('VY Canis Majoris', 'Milky Way', 'Star');
CALL insert_celestial_body('UY Scuti', 'Milky Way', 'Star');
CALL insert_celestial_body('Stephenson 2-18', 'Milky Way', 'Star');
CALL insert_celestial_body('Sagittarius A*', 'Milky Way', 'Black Hole'); -- Black hole at center of Milky Way


