CALL insert_celestial_body('Proxima Centauri b', 'Proxima Centauri', 'Planet');
CALL insert_celestial_body('Proxima Centauri c', 'Proxima Centauri', 'Planet');
CALL insert_celestial_body('Tau Ceti e', 'Tau Ceti', 'Planet');
CALL insert_celestial_body('Tau Ceti f', 'Tau Ceti', 'Planet');
CALL insert_celestial_body('Epsilon Eridani b', 'Epsilon Eridani', 'Planet');
CALL insert_celestial_body('TRAPPIST-1b', 'TRAPPIST-1', 'Planet');
CALL insert_celestial_body('TRAPPIST-1c', 'TRAPPIST-1', 'Planet');
CALL insert_celestial_body('TRAPPIST-1d', 'TRAPPIST-1', 'Planet');
CALL insert_celestial_body('TRAPPIST-1e', 'TRAPPIST-1', 'Planet');
CALL insert_celestial_body('TRAPPIST-1f', 'TRAPPIST-1', 'Planet');
CALL insert_celestial_body('TRAPPIST-1g', 'TRAPPIST-1', 'Planet');
CALL insert_celestial_body('TRAPPIST-1h', 'TRAPPIST-1', 'Planet');
CALL insert_celestial_body('Kepler-186f', 'Kepler-186', 'Planet');
CALL insert_celestial_body('Kepler-22b', 'Kepler-22', 'Planet');
CALL insert_celestial_body('Gliese 581d', 'Gliese 581', 'Planet');
CALL insert_celestial_body('Gliese 581g', 'Gliese 581', 'Planet');
CALL insert_celestial_body('Gliese 667 Cc', 'Gliese 687', 'Planet');
CALL insert_celestial_body('Gliese 832c', 'Gliese 832', 'Planet');
CALL insert_celestial_body('HD 219134 b', 'HD 219134', 'Planet');
CALL insert_celestial_body('Ross 128 b', 'Ross 128', 'Planet');
CALL insert_celestial_body('Wolf 1061c', 'Wolf 1061', 'Planet');
