CALL insert_star_system('Solar System', 'Sun');
CALL insert_star_system('Alpha Centauri System', 'Alpha Centauri A');
CALL insert_star_system('Sirius System', 'Sirius A');
CALL insert_star_system('Procyon System', 'Procyon A');
CALL insert_star_system('Epsilon Eridani System', 'Epsilon Eridani');
CALL insert_star_system('Tau Ceti System', 'Tau Ceti');
CALL insert_star_system('TRAPPIST-1 System', 'TRAPPIST-1');
CALL insert_star_system('Epsilon Indi System', 'Epsilon Indi A');
CALL insert_star_system('61 Cygni System', '61 Cygni A');
CALL insert_star_system('Struve 2398 System', 'Struve 2398 A');
CALL insert_star_system('Groombridge 34 System', 'Groombridge 34 A');
CALL insert_star_system('Kruger 60 System', 'Kruger 60 A');
CALL insert_star_system('Luyten 726-8 System', 'Luyten 726-8 A');
CALL insert_star_system('EZ Aquarii System', 'EZ Aquarii A');
CALL insert_star_system('Proxima Centauri System', 'Proxima Centauri');
CALL insert_star_system('Barnard''s Star System', 'Barnard''s Star');
CALL insert_star_system('Wolf 359 System', 'Wolf 359');
CALL insert_star_system('Lalande 21185 System', 'Lalande 21185');
CALL insert_star_system('Ross 128 System', 'Ross 128');
CALL insert_star_system('Lacaille 9352 System', 'Lacaille 9352');
CALL insert_star_system('Ross 154 System', 'Ross 154');
CALL insert_star_system('Luyten''s Star System', 'Luyten''s Star');
CALL insert_star_system('Teegarden''s Star System', 'Teegarden''s Star');
CALL insert_star_system('Kapteyn''s Star System', 'Kapteyn''s Star');
CALL insert_star_system('Wolf 1061 System', 'Wolf 1061');
CALL insert_star_system('Gliese 674 System', 'Gliese 674');
CALL insert_star_system('Gliese 687 System', 'Gliese 687');
CALL insert_star_system('Gliese 876 System', 'Gliese 876');
CALL insert_star_system('Gliese 832 System', 'Gliese 832');
CALL insert_star_system('Gliese 682 System', 'Gliese 682');
CALL insert_star_system('Gliese 581 System', 'Gliese 581');
CALL insert_star_system('Gliese 436 System', 'Gliese 436');
CALL insert_star_system('HD 219134 System', 'HD 219134');
CALL insert_star_system('Kepler-186 System', 'Kepler-186');
CALL insert_star_system('Kepler-22 System', 'Kepler-22');
