name: CLI Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build CLI
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup .NET 9.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.203
      
      - name: Restore dependencies
        run: dotnet restore src/GalaxyWiki.CLI/GalaxyWiki.CLI.csproj
      
      - name: Build CLI (Debug)
        run: dotnet build src/GalaxyWiki.CLI/GalaxyWiki.CLI.csproj --configuration Debug --no-restore
      
      - name: Test CLI
        run: dotnet test src/GalaxyWiki.Tests/GalaxyWiki.Tests.csproj --filter "Category=CLI" --configuration Debug
      
      - name: Publish CLI (.NET - cross platform)
        run: dotnet publish src/GalaxyWiki.CLI/GalaxyWiki.CLI.csproj -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true /p:PublishTrimmed=true -o ./publish/win-x64
      
      - name: Publish CLI (Linux x64)
        run: dotnet publish src/GalaxyWiki.CLI/GalaxyWiki.CLI.csproj -c Release -r linux-x64 --self-contained true /p:PublishSingleFile=true /p:PublishTrimmed=true -o ./publish/linux-x64
      
      - name: Publish CLI (macOS x64)
        run: dotnet publish src/GalaxyWiki.CLI/GalaxyWiki.CLI.csproj -c Release -r osx-x64 --self-contained true /p:PublishSingleFile=true /p:PublishTrimmed=true -o ./publish/osx-x64
      
      - name: Create .env.example for each platform
        run: |
          cp src/GalaxyWiki.CLI/.env.example ./publish/win-x64/
          cp src/GalaxyWiki.CLI/.env.example ./publish/linux-x64/
          cp src/GalaxyWiki.CLI/.env.example ./publish/osx-x64/
      
      - name: Create README for releases
        run: |
          cat > ./publish/README.md << 'EOF'
          # GalaxyWiki CLI

          This is the command-line interface for GalaxyWiki. It allows you to browse, search, and manage celestial bodies and star systems.

          ## Getting Started

          1. Rename `.env.example` to `.env` and configure your API settings
          2. Run the executable for your platform (`GalaxyWiki.CLI` or `GalaxyWiki.CLI.exe`)
          3. Type `help` to see available commands

          ## Key Commands

          - `help` - Display available commands
          - `login` - Authenticate with Google
          - `ls` - List celestial bodies at current location
          - `cd <location>` - Navigate to a location
          - `show` - Display information about current location
          - `search <term>` - Search for celestial bodies
          - `comment` - View and manage comments
          - `chat` - Launch interactive AI chatbot

          For more information, visit the [GalaxyWiki repository](https://github.com/yourusername/GalaxyWiki).
          EOF
          
          cp ./publish/README.md ./publish/win-x64/
          cp ./publish/README.md ./publish/linux-x64/
          cp ./publish/README.md ./publish/osx-x64/
      
      - name: Zip Windows release
        run: cd ./publish/win-x64 && zip -r ../../galaxywiki-cli-windows.zip *
      
      - name: Zip Linux release
        run: cd ./publish/linux-x64 && tar -czvf ../../galaxywiki-cli-linux.tar.gz *
      
      - name: Zip macOS release
        run: cd ./publish/osx-x64 && tar -czvf ../../galaxywiki-cli-macos.tar.gz *
      
      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: GalaxyWiki CLI v${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false
          files: |
            ./galaxywiki-cli-windows.zip
            ./galaxywiki-cli-linux.tar.gz
            ./galaxywiki-cli-macos.tar.gz
          body: |
            # GalaxyWiki CLI v${{ steps.get_version.outputs.VERSION }}
            
            ## Installation
            
            1. Download the appropriate package for your platform
            2. Extract the archive
            3. Rename `.env.example` to `.env` and configure your settings
            4. Run the executable
            
            ## What's New
            
            - Release of GalaxyWiki CLI v${{ steps.get_version.outputs.VERSION }} 