name: Migrations

on:
  push:
    branches:
      - main

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Flyway migrations
        run: |
          echo "Running Flyway migrations..."
          # Print Flyway version
          docker run --rm flyway/flyway:latest -v
          
          echo "Attempting database connection..."
          docker run --rm \
          -v $(pwd):/flyway/sql \
          flyway/flyway:latest \
          -url=jdbc:postgresql://${{ secrets.DB_URL }}:${{ secrets.DB_PORT }}/${{ secrets.DB_NAME }} \
          -user=${{ secrets.DB_USERNAME }} \
          -password=${{ secrets.DB_PASSWORD }} \
          -connectRetries=3 \
          -connectRetriesInterval=10 \
          info

          echo "Running migrations..."
          docker run --rm \
          -v $(pwd):/flyway/sql \
          flyway/flyway:latest \
          -url=jdbc:postgresql://${{ secrets.DB_URL }}:${{ secrets.DB_PORT }}/${{ secrets.DB_NAME }} \
          -user=${{ secrets.DB_USERNAME }} \
          -password=${{ secrets.DB_PASSWORD }} \
          -connectRetries=3 \
          -connectRetriesInterval=10 \
          -locations=filesystem:/flyway/sql/Migrations \
          migrate
