name: Deploy API

on:
  push:
    branches:
      - main
      - tevlen-prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x
      
      - name: Publish
        run: dotnet publish src/GalaxyWiki.API/GalaxyWiki.API.csproj -c Release -o ./publish
      
      - name: Generate deployment package
        run: |
          cd publish
          zip -r ../deploy.zip .
          cd ..
      
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: Galaxy-Wiki
          environment_name: Galaxy-Wiki-Prod
          version_label: v${{ github.run_number }}
          region: eu-west-1
          deployment_package: deploy.zip 