name: Migrations

on:
  push:
    branches:
      - main
      - tevlen-migrations

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Flyway migrations
        run: |
          echo "Running Flyway migrations..."
          docker run --rm \
          -v $(pwd):/flyway/sql \
          flyway/flyway:latest \
          -url=${{ secrets.DB_URL }} \
          -user=${{ secrets.DB_USER }} \
          -password=${{ secrets.DB_PASSWORD }} \
          -locations=filesystem:/flyway/sql/src/GalaxyWiki.Infrastructure/Migrations \
          migrate
